### ISSUE TITLE
Limit number of columns in the table

### ISSUE THREAD

**Issue by JAvRZ** [andi-nl/andi-vis#10]
Are two tables possible? (Avoids repeats of multivariate T)
Table 1:
"id"
"plotname"
"univariatedifferences"
"univariateT"
"univariatedf"
"univariatep"

Table 2.
"id"
"plotname"
"multivariatedifference":
"multivariateT"
"multivariatedf"
"multivariatep"

**Comment by mkuzak** [comment]
reolved by 2f010f1bd92013e9fa266d2b2280b9dc7278b9a8
