### ISSUE TITLE
Better, human readable column names

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/andi-vis#11]

**Comment by JAvRZ** [comment]
Table 1
id -> patient
plotname -> test variable name
univariatedifferences -> difference
univariateT -> t-value
univariatedf -> degrees of freedom
univariatep -> p-value

Table 1
id -> patient
multivariatedifference -> sum of differences
multivariateT -> multivariate statistic
multivariatedf -> degrees of freedom
multivariatep -> p-value

**Comment by mkuzak** [comment]
I suggest `plotname -> test variable`
it's shorter
